hpc <- read.table("household_power_consumption.txt", sep=";", header = TRUE)
hpc$DateTime <- paste(hpc$Date,hpc$Time)
hpc$DateTime <- strptime(hpc$DateTime, "%d/%m/%Y %H:%M:%S")
household_power_consumption <- subset(hpc, DateTime > "2007-01-31 23:59:59" & DateTime < "2007-02-03 00:00:00")
household_power_consumption$Global_active_power <- as.numeric(as.character(household_power_consumption$Global_active_power))
household_power_consumption$Global_reactive_power <- as.numeric(as.character(household_power_consumption$Global_reactive_power))
household_power_consumption$Voltage <- as.numeric(as.character(household_power_consumption$Voltage))
household_power_consumption$Global_intensity <- as.numeric(as.character(household_power_consumption$Global_intensity))
household_power_consumption$Sub_metering_1 <- as.numeric(as.character(household_power_consumption$Sub_metering_1))
household_power_consumption$Sub_metering_2 <- as.numeric(as.character(household_power_consumption$Sub_metering_2))
windows()
png(file="plot2.png")
plot(household_power_consumption$DateTime, household_power_consumption$Global_active_power, type="l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()